// <auto-generated />
using System;
using KutuphaneOtomasyon.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;


#nullable disable

namespace KutuphaneOtomasyon.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250705094016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KutuphaneOtomasyon.Web.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KategoriID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KategoriID");

                    b.ToTable("kategoriler", (string)null);
                });

            modelBuilder.Entity("KutuphaneOtomasyon.Web.Models.Kitap", b =>
                {
                    b.Property<int>("KitapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KitapID"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KategoriID")
                        .HasColumnType("integer");

                    b.Property<int>("MevcutAdet")
                        .HasColumnType("integer");

                    b.Property<int?>("YayinYili")
                        .HasColumnType("integer");

                    b.Property<int>("YayineviID")
                        .HasColumnType("integer");

                    b.Property<int>("YazarID")
                        .HasColumnType("integer");

                    b.HasKey("KitapID");

                    b.HasIndex("KategoriID");

                    b.HasIndex("YayineviID");

                    b.HasIndex("YazarID");

                    b.ToTable("kitaplar", (string)null);
                });

            modelBuilder.Entity("KutuphaneOtomasyon.Web.Models.OduncAlma", b =>
                {
                    b.Property<int>("OduncAlmaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OduncAlmaID"));

                    b.Property<DateTime?>("BeklenenIadeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GercekIadeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KitapID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OduncAlmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UyeID")
                        .HasColumnType("integer");

                    b.HasKey("OduncAlmaID");

                    b.HasIndex("KitapID");

                    b.HasIndex("UyeID");

                    b.ToTable("odunc_almalar", (string)null);
                });

            modelBuilder.Entity("KutuphaneOtomasyon.Web.Models.Personel", b =>
                {
                    b.Property<int>("PersonelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonelID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonelID");

                    b.ToTable("personel", (string)null);
                });

            modelBuilder.Entity("KutuphaneOtomasyon.Web.Models.Uye", b =>
                {
                    b.Property<int>("UyeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UyeID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UyeID");

                    b.ToTable("uyeler", (string)null);
                });

            modelBuilder.Entity("KutuphaneOtomasyon.Web.Models.Yayinevi", b =>
                {
                    b.Property<int>("YayineviID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("YayineviID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("YayineviID");

                    b.ToTable("yayinevleri", (string)null);
                });

            modelBuilder.Entity("KutuphaneOtomasyon.Web.Models.Yazar", b =>
                {
                    b.Property<int>("YazarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("YazarID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("YazarID");

                    b.ToTable("yazarlar", (string)null);
                });

            modelBuilder.Entity("KutuphaneOtomasyon.Web.Models.Kitap", b =>
                {
                    b.HasOne("KutuphaneOtomasyon.Web.Models.Kategori", "Kategori")
                        .WithMany("Kitaplar")
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KutuphaneOtomasyon.Web.Models.Yayinevi", "Yayinevi")
                        .WithMany("Kitaplar")
                        .HasForeignKey("YayineviID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KutuphaneOtomasyon.Web.Models.Yazar", "Yazar")
                        .WithMany("Kitaplar")
                        .HasForeignKey("YazarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Yayinevi");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("KutuphaneOtomasyon.Web.Models.OduncAlma", b =>
                {
                    b.HasOne("KutuphaneOtomasyon.Web.Models.Kitap", "Kitap")
                        .WithMany("OduncAlmalar")
                        .HasForeignKey("KitapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KutuphaneOtomasyon.Web.Models.Uye", "Uye")
                        .WithMany("OduncAlmalar")
                        .HasForeignKey("UyeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("KutuphaneOtomasyon.Web.Models.Kategori", b =>
                {
                    b.Navigation("Kitaplar");
                });

            modelBuilder.Entity("KutuphaneOtomasyon.Web.Models.Kitap", b =>
                {
                    b.Navigation("OduncAlmalar");
                });

            modelBuilder.Entity("KutuphaneOtomasyon.Web.Models.Uye", b =>
                {
                    b.Navigation("OduncAlmalar");
                });

            modelBuilder.Entity("KutuphaneOtomasyon.Web.Models.Yayinevi", b =>
                {
                    b.Navigation("Kitaplar");
                });

            modelBuilder.Entity("KutuphaneOtomasyon.Web.Models.Yazar", b =>
                {
                    b.Navigation("Kitaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
